export const employees = [
  {
    name: "Jennifer Malone",
    email: "evansbrittany@example.org",
    designation: "VP",
    reporting_manager: "michaelyork@example.com",
    team: "Comedy",
  },
  {
    name: "Jonathan King",
    email: "christopher03@example.org",
    designation: "VP",
    reporting_manager: "michaelyork@example.com",
    team: "Staging",
  },
  {
    name: "Mary Wyatt",
    email: "donnabell@example.org",
    designation: "Director",
    reporting_manager: "christopher03@example.org",
    team: "Retail",
  },
  {
    name: "Pamela Ortega MD",
    email: "christy26@example.org",
    designation: "Director",
    team: "Retail",
    reporting_manager: "christopher03@example.org",
  },
  {
    name: "Lori Hall",
    email: "melissamccullough@example.org",
    designation: "Engineer",
    team: "Retail",
    reporting_manager: "christy26@example.org",
  },
  {
    name: "Megan Wilson",
    email: "kristinthompson@example.org",
    designation: "Director",
    team: "Retail",
    reporting_manager: "christopher03@example.org",
  },
  {
    name: "Christine Matthews",
    email: "ithomas@example.net",
    designation: "Engineer",
    reporting_manager: "kristinthompson@example.org",
    team: "Staging",
  },
  {
    name: "Nathan Hess",
    email: "urichards@example.net",
    designation: "Designer",
    reporting_manager: "ithomas@example.net",
    team: "Sales",
  },
  {
    name: "Kyle Bryant",
    email: "angela80@example.net",
    designation: "Helper",
    reporting_manager: "urichards@example.net",
    team: "Sales",
  },

  {
    name: "Dr. Matthew Neal MD",
    email: "wendymccullough@example.com",
    designation: "Oncologist",
    reporting_manager: "ithomas@example.net",
    team: "Health",
  },
  {
    name: "Kerry Walsh",
    email: "zpierce@example.org",
    designation: "Mangager",
    reporting_manager: "ithomas@example.net",
    team: "Sales",
  },
  {
    name: "Mary Lucas",
    email: "kathleencoleman@example.org",
    designation: "Comedy",
    reporting_manager: "zpierce@example.org",
    team: "Staging",
  },
  {
    name: "Katie Schwartz",
    email: "vaughnlisa@example.com",
    designation: "Teacher",
    reporting_manager: "ithomas@example.net",
    team: "Education",
  },
  {
    name: "Benjamin Alexander",
    email: "youngashley@example.net",
    designation: "Developer",
    reporting_manager: "vaughnlisa@example.com",
    team: "Engineering",
  },
  {
    name: "Michael Nunez",
    email: "anna04@example.org",
    designation: "Comedy",
    reporting_manager: "youngashley@example.net",
    team: "Humour",
  },
  {
    name: "David Jordan",
    email: "michaelyork@example.com",
    designation: "CTO",
    team: "Board",
  },
];
